name: "🚀 publish"

on:
    push:
        branches:
          - main
     
permissions:
    id-token: write
    contents: read

jobs:
    release:
        name: 🚀 publish
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v6

            - name: 🟢 node
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  registry-url: https://registry.npmjs.org

            - name: 🛠️ setup unity-cli & upm-cli
              run: |
                npm install -g @rage-against-the-pixel/unity-cli
                unity-cli upm-install

            - name: 🔏 sign unity package
              env:
                UPM_ENTERPRISE_ORGANIZATION_ID: ${{ secrets.UNITY_ORG_ID }}
                UPM_SERVICE_ACCOUNT_KEY_ID: ${{ secrets.UPM_SERVICE_ACCOUNT_KEY_ID }}
                UPM_SERVICE_ACCOUNT_KEY_SECRET: ${{ secrets.UPM_SERVICE_ACCOUNT_KEY_SECRET }}
              run: |
                # Call the upm tool installed to the local environment path
                ~/.unity-cli/upm package sign .

            # --- Publish with npm Provenance ---
            - name: 🚀 publish
              run: npm publish --access public --provenance
